version: '3.9'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    restart: always
  server:
    image: server:latest
    build: server/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'
    restart: always
    depends_on:
      - postgres
  client:
    image: client:latest
    build: client/.
    environment:
      SPRING_PROFILES_ACTIVE: docker
    restart: always
    depends_on:
      - server